$('.sitel').removeClass('fl');
$('.sitel').addClass('fr');
$('.sitel').css('text-align','left');
$('.sitel').removeClass('fl');
$('.sitel').addClass('fr');
$('.sitel').css('text-align','left');
$(`<img src="https://abo-arish.net/sico/1669820901787.gif" class="fr" style="width:99.5%;margin-top: 0px;" ></a> `).insertBefore('.nav-tabs');
$('.fa-gear').text('الضبط') 
$(` </style><link rel="stylesheet" type="text/css" href="//www.fontstatic.com/f=jazeera-light,jazeera"> <link rel="stylesheet" href="https://rawcdn.githack.com/majedd1/new/ee192e4921f6f756de3ddcd167c707e0dcd06a75/113.css"> </style>`).insertBefore('body');
$(`<style>  
button.btn.fr.btn-success.fa.fa-refresh{display:none} .fl.ustat { border-radius: 15px 0!important; width: 6px!important; margin:5px }  .ae.fa.chats.label.fa-comment.label-primary {border-radius: 0px 0px 0px 0px!important} .ae.fa.label.label-primary.fa-user {border-radius: 30px 0px 0px 30px!important;} .ae.fa.label.label-primary.fa-users {border-radius: 0px 0px 0px 0px!important;margin-left: 0px!important;}
.light.fl.pro.center.break .fl.u-msg { width: 95% !important; padding: 10px !important; text-align: center !important; outline-offset: -6px; border-radius: 5px; border: 1px solid #2c2c2c; box-shadow: 8px 3px 5px -3px #000; margin-bottom: 30px; margin-left: 7px; overflow: auto; height: 79px; background: #ebebeb87; margin-top: 10px; font-size: 14px !important; } .corner.fa.fa-user.label.label-primary.fr.uc{width:80px!important}fitimg.fl.u-pic {box-shadow: 0 1px 1px -1px rgb(137, 137, 137), 0 0 5px rgb(137, 137, 137);border-radius: 5px 5px 5px 5px;;}
.img.fitimg.fl.u-pic { padding: 0; border-radius: 3px; margin-right: 5px; box-shadow: inset 1px 1px 1px 1px ,0 0 5px # }img.fitimg.fl.u-pic { padding: 0; border-radius: 3px; margin-right:0px; box-shadow: inset 1px 1px 1px 1px ,0 0 5px # } 
textarea.fl.filw.corner.tbox { box-shadow:inset 0 2px 2px rgb(218, 218, 218), 0 0 8px rgb(21, 47, 94);border-radius: 7px;padding-left: 5px;} 
span.bwall.minix.badge.border,span.brooms.minix.badge.border{display:none!important} 
.fl.fa.fa-sign-in.btn.btn-primary.dots.roomh.border.corner{padding:1px 4px!important;pointer-events:none}
ae.fa.label.label-primary.fa-users{border-right-width:medium padding:7px 5px 5px 13px;border-radius:0;margin-left:-3px!important}.fl.fa.fa-sign-in.btn.btn-primary.dots.roomh.border.corner{padding:1px 4px!important;pointer-events:none}
.broadcasters>div>.prod{background-image:url(sico/);border-radius:-5px 5px!important}
.broadcasters {   background: #051626 !important;border-bottom: 2px solid #ca918f !important;background-image: url(sico/1671757793343.jpg)!important;} 
div#l1, div#l2, div#l3 {    border-bottom: 2px solid;margin-bottom: 15px;border-top: 4px solid;margin-top: 0;    border-color: #1f1f26;font-family: jazeera,FontAwesome;border-bottom: 2px solid;margin-bottom: 15px;border-top: 4px solid;margin-top: 0;border-color: #1f1f26;    font-family: jazeera,FontAwesome;border-bottom: 2px solid;margin-bottom: 2px;    border-top: 4px solid;margin-top: 0; border-color: #1f1f26;border-radius: 15px;height: 70px;font-family: jazeera,FontAwesome;   width: 101%;border-right: ridge; border-left: ridge;position: relative;/* top: -47px; */    background: -webkit-linear-gradient( 332deg ,rgba(166,206,214,0) 25%,transparent 0,rgba(43,135,153,0) 50%,hsla(0,0%,100%,.2) 0,hsla(0,0%,100%,.2) 75%,transparent 0,transparent)!important;background-color: #e8e8e8 !important;}div#tlogins ::-webkit-scrollbar {width: 5px;height: 10px;}
div#tlogins ::-webkit-scrollbar-button {width: 20px;    height: 5px;}div#tlogins ::-webkit-scrollbar-corner {background: #000;}::-webkit-scrollbar-corner {background: transparent;}div#tlogins ::-webkit-scrollbar-thumb {background: #050505;    border: 71px none #fff;border-radius: 31px;    background-image: -webkit-linear-gradient( 45deg ,rgba(255,255,255,.2) 25%,transparent 25%,transparent 50%,rgba(255,255,255,.2) 50%,rgba(255,255,255,.2) 75%,transparent 75%,transparent)!important;}div#tlogins ::-webkit-scrollbar-track {background: #fff;    border: 65px none #fff; border-radius: 34px;}::-webkit-scrollbar-track { background: #f8f9fa; border: 65px none #fff;border-radius: 34px;}.fr.borderg {font-size: 10px!important;padding: 0 5px!important;position: relative;color: #47749b;}div#l1 input#u1 {width: 85%;    height: 35px;margin-bottom: .2rem; font-size: .9rem;padding: 0 .5em;text-align: left; color: #ae0b0a;margin-left: 28px;margin-top: 2px;    border-radius: 10px 0 10px 0;border: 2px solid #ddd!important;box-shadow: inset 8px 8px 8px #cbced1, inset -8px -8px 8px #fff;    font-family: jazeera,FontAwesome;}div#l2 input#u2, div#l3 input#u3 {width: 35%;    height: 35px;margin-bottom: .2rem; font-size: .9rem;padding: 0 .5em;text-align: left;    color: #ae0b0a;margin-top: 2px; border-radius: 10px 0 10px 0;border: 2px solid #ddd!important;    box-shadow: inset 8px 8px 8px #cbced1, inset -8px -8px 8px #fff;font-family: jazeera,FontAwesome;}div#l2 input#pass1, div#l3 input#pass2 {width: 68%;height: 35px;margin-bottom: .2rem;font-size: .9rem;padding: 0 .5em;text-align: left; color: #ae0b0a;margin-top: 2px;border-radius: 10px 0 10px 0;border: 2px solid #ddd!important;    box-shadow: inset 8px 8px 8px #cbced1, inset -8px -8px 8px #fff;font-family: jazeera,FontAwesome;} 
ae.fa.label.label-primary.fa-users{border-right-width:medium padding:7px 5px 5px 13px;border-radius:0;margin-left:-3px!important}a.label.label-primary.fl{border-radius:3px!important;padding:5px!important;margin-bottom:2px;text-align:Center!important}#des22{text-align:center!important;font-size:100%!important} fr.borderg,.fr.borderg a{font-size:10px!important;padding:0 5px!important;position:relative;color:#47749b} 
</style>`).insertBefore('body'); 
